# Generated by Django 4.2.24 on 2025-09-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_massage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
