# Generated by Django 4.2.24 on 2025-11-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_30', models.IntegerField(blank=True, null=True)),
                ('price_60', models.IntegerField(blank=True, null=True)),
                ('price_90', models.IntegerField(blank=True, null=True)),
                ('price_120', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
