# Generated by Django 5.2.8 on 2025-12-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'รออนุมัติ'), ('confirmed', 'ยืนยันแล้ว'), ('cancelled', 'ยกเลิกแล้ว')], default='pending', max_length=20),
        ),
    ]
