# Generated by Django 5.2.8 on 2025-12-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo_mime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='massage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='massage',
            name='duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='massage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='massage_images/'),
        ),
        migrations.AlterField(
            model_name='massage',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
