# Generated by Django 5.2.8 on 2026-01-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_massage_description_de_massage_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='massage',
            name='description_de',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='massage',
            name='description_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='massage',
            name='name_de',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='massage',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
