# Generated by Django 5.2.10 on 2026-02-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_massage_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='price_120',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='massage',
            name='price_30',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='massage',
            name='price_60',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='massage',
            name='price_90',
            field=models.IntegerField(default=0),
        ),
    ]
